##eureka
eureka:
  instance:
    ##约定服务续约时间间隔
    lease-renewal-interval-in-seconds: 5
    ##约定服务失效时间间隔(xx秒无续约请求则失效)
    lease-expiration-duration-in-seconds: 10
  client:
    ##客户端允许获取注册清单
    fetch-registry: true
    ##客户端重新获取注册清单时间间隔
    registry-fetch-interval-seconds: 30